# Generated by Django 4.2.6 on 2023-10-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temp_Profile_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        upload_to="temp_images", verbose_name="temp_profile_image"
                    ),
                ),
            ],
        ),
    ]
